sonar.projectKey=vertexbank-backend
sonar.projectName=VertexBank Backend
sonar.projectVersion=1.0.0
sonar.sources=AuthService/src/main/java,UserService/src/main/java
sonar.tests=AuthService/src/test/java,UserService/src/test/java
sonar.sourceEncoding=UTF-8
sonar.java.source=21
sonar.java.target=21
sonar.exclusions=**/model/**,**/entity/**,**/dto/**,**/config/**,**/*Application.java,**/exception/**
sonar.coverage.jacoco.xmlReportPaths=AuthService/target/site/jacoco/jacoco.xml,UserService/target/site/jacoco/jacoco.xml
sonar.java.binaries=AuthService/target/classes,UserService/target/classes
