spring.application.name=accountservice
server.port=8083

user-service.url=http://localhost:8082

# Banco de Dados
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5439/account_db?sslmode=disable}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Docker
spring.docker.compose.enabled=true

# JWT Secret
security.jwt.secret-key=${JWT_SECRET}
